name: education_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  
  chewie: ^1.8.3
  cloud_firestore: ^5.4.2
  cupertino_icons: ^1.0.6
  
  dartz: ^0.10.1
  equatable: ^2.0.5
  file_picker: ^8.1.2
  firebase_auth: 5.3.0
  firebase_core: 3.5.0
  firebase_storage: ^12.3.1
  firebase_ui_auth: ^1.15.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  font_awesome_flutter: ^10.5.0
  get_it: ^7.6.0
  iconly: ^1.0.1
  image_picker: ^1.0.2
  intl: ^0.19.0
  lottie: ^3.0.0
  open_file: ^3.3.2
  path_provider: ^2.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  smooth_page_indicator: ^1.1.0
  swipe_to: ^1.0.2
  url_launcher: ^6.1.12
  uuid: ^4.5.0
  video_thumbnail: ^0.5.3
  
  

dev_dependencies:
  

  bloc_test: ^9.1.4
  fake_cloud_firestore: ^3.0.3
  firebase_auth_mocks: ^0.14.1
  firebase_storage_mocks: ^0.7.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  google_sign_in_mocks: ^0.3.0
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0+1

flutter:

  uses-material-design: true


  assets:
    - assets/vectors/
    - assets/images/
    - assets/lottie/
    - assets/icons/

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
